[package]
name = "test-parachain-halt"
version = "0.8.13"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which executes forever"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = [ "std" ]
std = []
